[package]
name = "vds"
version = "0.1.0"
authors = ["solarsail <newleaf.lu@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
rustc-serialize = "*"
iron-pipeline = { git = "https://github.com/deadalusai/iron-pipeline" }